CASES = [
    {
        "id": "CASE-001",
        "title": "VLAN 30 cannot reach server",
        "description": "PC gets an IP address but cannot reach the server in VLAN 30. Gateway ping works.",
        "category": "VLAN",
        "severity": "High",
        "layer": "Layer 2",
        "show_outputs": "show vlan brief\nshow interfaces trunk",
        "expected_fault": "VLAN configuration or trunking problem",
        "root_cause": "VLAN 30 is missing from the trunk allowed VLAN list.",
        "fix": "Add VLAN 30 to the trunk allowed VLAN list.",
        "confidence": 91
    },
    {
        "id": "CASE-002",
        "title": "PC receives no DHCP address",
        "description": "PC receives a 169.254.x.x address instead of a valid network address.",
        "category": "DHCP",
        "severity": "High",
        "layer": "Layer 2/3",
        "show_outputs": "ipconfig /all\nshow ip dhcp pool",
        "expected_fault": "DHCP service or relay problem",
        "root_cause": "DHCP relay is missing on the client VLAN interface.",
        "fix": "Configure the correct ip helper-address.",
        "confidence": 94
    },
    {
        "id": "CASE-003",
        "title": "DNS name resolution fails",
        "description": "User can ping an IP address but cannot access websites using domain names.",
        "category": "DNS",
        "severity": "Medium",
        "layer": "Layer 7",
        "show_outputs": "ipconfig /all\nnslookup example.com",
        "expected_fault": "DNS configuration problem",
        "root_cause": "The client has an incorrect DNS server address.",
        "fix": "Configure the correct DNS server address.",
        "confidence": 92
    },
    {
        "id": "CASE-004",
        "title": "Default route missing",
        "description": "The local network works but users cannot access remote networks or the internet.",
        "category": "Routing",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show ip route",
        "expected_fault": "Missing default route",
        "root_cause": "The router has no default route toward the ISP.",
        "fix": "Configure the correct default route.",
        "confidence": 96
    },
    {
        "id": "CASE-005",
        "title": "ACL blocks web traffic",
        "description": "Users can ping the server but HTTP access fails.",
        "category": "ACL",
        "severity": "High",
        "layer": "Layer 3/4",
        "show_outputs": "show access-lists\nshow running-config",
        "expected_fault": "ACL blocking HTTP traffic",
        "root_cause": "The ACL denies TCP port 80 traffic.",
        "fix": "Modify the ACL to permit required HTTP traffic.",
        "confidence": 93
    },
    {
        "id": "CASE-006",
        "title": "Switch port is down",
        "description": "A connected PC has no network connectivity.",
        "category": "Switching",
        "severity": "High",
        "layer": "Layer 2",
        "show_outputs": "show interfaces status",
        "expected_fault": "Interface is administratively down",
        "root_cause": "The switch port is shut down.",
        "fix": "Enable the interface using no shutdown.",
        "confidence": 97
    },
    {
        "id": "CASE-007",
        "title": "Wrong access VLAN",
        "description": "The PC connects but receives an address from the wrong network.",
        "category": "VLAN",
        "severity": "Medium",
        "layer": "Layer 2",
        "show_outputs": "show vlan brief\nshow interfaces switchport",
        "expected_fault": "Incorrect access VLAN",
        "root_cause": "The switch port is assigned to the wrong VLAN.",
        "fix": "Assign the port to the correct access VLAN.",
        "confidence": 95
    },
    {
        "id": "CASE-008",
        "title": "Trunk link not forming",
        "description": "VLANs cannot communicate between two switches.",
        "category": "VLAN",
        "severity": "High",
        "layer": "Layer 2",
        "show_outputs": "show interfaces trunk\nshow interfaces switchport",
        "expected_fault": "Trunk configuration mismatch",
        "root_cause": "One side of the link is configured as an access port.",
        "fix": "Configure both sides correctly as a trunk.",
        "confidence": 94
    },
    {
        "id": "CASE-009",
        "title": "Inter-VLAN routing fails",
        "description": "Devices in different VLANs cannot communicate.",
        "category": "Routing",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show ip interface brief\nshow ip route",
        "expected_fault": "Inter-VLAN routing problem",
        "root_cause": "The router subinterface for the VLAN is missing.",
        "fix": "Configure the required VLAN subinterface.",
        "confidence": 91
    },
    {
        "id": "CASE-010",
        "title": "DHCP pool exhausted",
        "description": "New clients cannot obtain IP addresses.",
        "category": "DHCP",
        "severity": "Medium",
        "layer": "Layer 3",
        "show_outputs": "show ip dhcp pool\nshow ip dhcp binding",
        "expected_fault": "DHCP address pool exhausted",
        "root_cause": "The DHCP pool has no available addresses.",
        "fix": "Expand the DHCP address pool.",
        "confidence": 96
    },
    {
        "id": "CASE-011",
        "title": "Incorrect subnet mask",
        "description": "A host can reach some devices but not devices on the expected subnet.",
        "category": "IP Addressing",
        "severity": "Medium",
        "layer": "Layer 3",
        "show_outputs": "ipconfig /all",
        "expected_fault": "Incorrect subnet mask",
        "root_cause": "The host has an incorrect subnet mask.",
        "fix": "Configure the correct subnet mask.",
        "confidence": 93
    },
    {
        "id": "CASE-012",
        "title": "Wrong default gateway",
        "description": "The PC can communicate locally but cannot reach remote networks.",
        "category": "Gateway",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "ipconfig /all",
        "expected_fault": "Incorrect default gateway",
        "root_cause": "The PC is configured with the wrong gateway address.",
        "fix": "Configure the correct default gateway.",
        "confidence": 97
    },
    {
        "id": "CASE-013",
        "title": "Static route missing",
        "description": "A remote network cannot be reached.",
        "category": "Routing",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show ip route",
        "expected_fault": "Missing static route",
        "root_cause": "The router has no route to the remote subnet.",
        "fix": "Add a route to the remote subnet.",
        "confidence": 96
    },
    {
        "id": "CASE-014",
        "title": "Wrong next hop",
        "description": "A route exists but packets do not reach the destination.",
        "category": "Routing",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show ip route",
        "expected_fault": "Incorrect next-hop address",
        "root_cause": "The configured next-hop IP address is incorrect.",
        "fix": "Change the route to the correct next-hop address.",
        "confidence": 94
    },
    {
        "id": "CASE-015",
        "title": "NAT translation missing",
        "description": "Internal users cannot access the internet.",
        "category": "NAT",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show ip nat translations\nshow ip nat statistics",
        "expected_fault": "NAT configuration problem",
        "root_cause": "The inside interface is not included in NAT configuration.",
        "fix": "Correct the NAT inside configuration.",
        "confidence": 92
    },
    {
        "id": "CASE-016",
        "title": "NAT overload not configured",
        "description": "Multiple internal hosts cannot share the public IP.",
        "category": "NAT",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show running-config\nshow ip nat translations",
        "expected_fault": "PAT configuration missing",
        "root_cause": "NAT overload is not configured.",
        "fix": "Configure NAT overload using the correct outside interface.",
        "confidence": 95
    },
    {
        "id": "CASE-017",
        "title": "Wireless client cannot connect",
        "description": "A laptop cannot associate with the wireless network.",
        "category": "Wireless",
        "severity": "Medium",
        "layer": "Layer 2",
        "show_outputs": "show wlan summary\nshow wireless client summary",
        "expected_fault": "Wireless configuration problem",
        "root_cause": "The wireless SSID is disabled.",
        "fix": "Enable the required SSID.",
        "confidence": 90
    },
    {
        "id": "CASE-018",
        "title": "Wireless client gets no IP",
        "description": "The laptop connects to Wi-Fi but receives no valid IP address.",
        "category": "Wireless",
        "severity": "High",
        "layer": "Layer 2/3",
        "show_outputs": "show wireless client summary\nshow ip dhcp binding",
        "expected_fault": "Wireless VLAN or DHCP problem",
        "root_cause": "The wireless network is mapped to the wrong VLAN.",
        "fix": "Map the wireless network to the correct VLAN.",
        "confidence": 89
    },
    {
        "id": "CASE-019",
        "title": "DNS server unreachable",
        "description": "Clients have IP addresses but DNS queries fail.",
        "category": "DNS",
        "severity": "Medium",
        "layer": "Layer 7",
        "show_outputs": "ping DNS-server\nnslookup example.com",
        "expected_fault": "DNS server connectivity problem",
        "root_cause": "The configured DNS server cannot be reached.",
        "fix": "Restore connectivity to the DNS server or configure another DNS server.",
        "confidence": 88
    },
    {
        "id": "CASE-020",
        "title": "ACL blocks DNS",
        "description": "Internet connectivity works by IP but domain names fail.",
        "category": "ACL",
        "severity": "Medium",
        "layer": "Layer 3/4",
        "show_outputs": "show access-lists",
        "expected_fault": "ACL blocks DNS traffic",
        "root_cause": "UDP port 53 is denied by the ACL.",
        "fix": "Permit DNS traffic in the ACL.",
        "confidence": 93
    },
    {
        "id": "CASE-021",
        "title": "Router interface down",
        "description": "A connected network is unreachable.",
        "category": "Gateway",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show ip interface brief",
        "expected_fault": "Router interface down",
        "root_cause": "The router interface is administratively down.",
        "fix": "Enable the interface.",
        "confidence": 98
    },
    {
        "id": "CASE-022",
        "title": "Duplicate IP address",
        "description": "Network connectivity is intermittent.",
        "category": "IP Addressing",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show arp\nipconfig /all",
        "expected_fault": "Duplicate IP configuration",
        "root_cause": "Two devices are using the same IP address.",
        "fix": "Assign unique IP addresses to the devices.",
        "confidence": 90
    },
    {
        "id": "CASE-023",
        "title": "ARP resolution failure",
        "description": "A host cannot reach a directly connected device.",
        "category": "ARP",
        "severity": "Medium",
        "layer": "Layer 2/3",
        "show_outputs": "show arp",
        "expected_fault": "ARP resolution problem",
        "root_cause": "The ARP entry for the destination is missing.",
        "fix": "Check Layer 2 connectivity and refresh ARP resolution.",
        "confidence": 87
    },
    {
        "id": "CASE-024",
        "title": "Port security violation",
        "description": "A switch port stops forwarding traffic after a new device is connected.",
        "category": "Switching",
        "severity": "High",
        "layer": "Layer 2",
        "show_outputs": "show port-security interface",
        "expected_fault": "Port security violation",
        "root_cause": "An unauthorized MAC address triggered port security.",
        "fix": "Verify the device and correct the port-security configuration.",
        "confidence": 95
    },
    {
        "id": "CASE-025",
        "title": "STP blocking expected traffic",
        "description": "A redundant switch path is not forwarding traffic.",
        "category": "STP",
        "severity": "Medium",
        "layer": "Layer 2",
        "show_outputs": "show spanning-tree",
        "expected_fault": "STP blocking port",
        "root_cause": "Spanning Tree has placed the redundant port into blocking state.",
        "fix": "Verify the STP topology and root bridge configuration.",
        "confidence": 86
    },
    {
        "id": "CASE-026",
        "title": "Incorrect VLAN allowed on trunk",
        "description": "One VLAN works but another VLAN cannot cross the trunk.",
        "category": "VLAN",
        "severity": "High",
        "layer": "Layer 2",
        "show_outputs": "show interfaces trunk",
        "expected_fault": "VLAN missing from trunk",
        "root_cause": "The required VLAN is not allowed on the trunk.",
        "fix": "Allow the required VLAN on the trunk.",
        "confidence": 96
    },
    {
        "id": "CASE-027",
        "title": "ACL blocks HTTPS",
        "description": "Users cannot access secure websites but ping works.",
        "category": "ACL",
        "severity": "High",
        "layer": "Layer 3/4",
        "show_outputs": "show access-lists",
        "expected_fault": "ACL blocks HTTPS",
        "root_cause": "TCP port 443 is denied by the ACL.",
        "fix": "Permit HTTPS traffic in the ACL.",
        "confidence": 94
    },
    {
        "id": "CASE-028",
        "title": "Routing protocol neighbor down",
        "description": "Dynamic routes disappear from the routing table.",
        "category": "Routing",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show ip ospf neighbor\nshow ip route",
        "expected_fault": "Routing neighbor problem",
        "root_cause": "The routing protocol neighbor relationship is down.",
        "fix": "Check interface addressing and routing protocol configuration.",
        "confidence": 88
    },
    {
        "id": "CASE-029",
        "title": "DHCP relay points to wrong server",
        "description": "Clients cannot obtain DHCP addresses.",
        "category": "DHCP",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show running-config interface\nshow ip dhcp binding",
        "expected_fault": "Incorrect DHCP relay address",
        "root_cause": "The ip helper-address points to the wrong DHCP server.",
        "fix": "Configure the correct DHCP server address.",
        "confidence": 95
    },
    {
        "id": "CASE-030",
        "title": "Guest Wi-Fi can access internal server",
        "description": "Guest users can reach an internal company server.",
        "category": "Wireless / ACL",
        "severity": "Critical",
        "layer": "Layer 3/4",
        "show_outputs": "show access-lists\nshow vlan brief",
        "expected_fault": "Guest isolation failure",
        "root_cause": "The ACL does not block guest traffic to the internal network.",
        "fix": "Add an ACL rule preventing guest access to internal networks.",
        "confidence": 92
    },
    {
        "id": "CASE-031",
        "title": "VLAN interface has wrong IP",
        "description": "Users in one VLAN cannot reach their gateway.",
        "category": "VLAN",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show ip interface brief\nshow running-config",
        "expected_fault": "Incorrect SVI address",
        "root_cause": "The VLAN interface has an incorrect IP address.",
        "fix": "Configure the correct SVI IP address.",
        "confidence": 93
    },
    {
        "id": "CASE-032",
        "title": "DHCP excluded address problem",
        "description": "The DHCP server has addresses configured but clients are not receiving them.",
        "category": "DHCP",
        "severity": "Medium",
        "layer": "Layer 3",
        "show_outputs": "show ip dhcp pool\nshow running-config",
        "expected_fault": "Incorrect DHCP exclusion",
        "root_cause": "Too many addresses have been excluded from the DHCP pool.",
        "fix": "Review and correct the excluded address range.",
        "confidence": 84
    },
    {
        "id": "CASE-033",
        "title": "NAT outside interface missing",
        "description": "Internal traffic reaches the router but internet access fails.",
        "category": "NAT",
        "severity": "High",
        "layer": "Layer 3",
        "show_outputs": "show running-config\nshow ip interface brief",
        "expected_fault": "NAT outside interface problem",
        "root_cause": "The internet-facing interface is not configured as NAT outside.",
        "fix": "Configure the correct interface as ip nat outside.",
        "confidence": 94
    },
    {
        "id": "CASE-034",
        "title": "Wireless guest network misconfigured",
        "description": "Guest users are placed into the corporate network.",
        "category": "Wireless",
        "severity": "Critical",
        "layer": "Layer 2/3",
        "show_outputs": "show wlan summary\nshow vlan brief",
        "expected_fault": "Incorrect guest VLAN mapping",
        "root_cause": "The guest SSID is mapped to the corporate VLAN.",
        "fix": "Map the guest SSID to an isolated guest VLAN.",
        "confidence": 96
    },
]